### ISSUE TITLE
Channel handling?

### ISSUE THREAD

**Issue by jbf81tb** [rbnvrw/nd2reader#12]
I think the way channels are handled is a bit funny, at least when it comes to the get_frame_2D function. You ask the user to pass an index for the metadata["channels"] list. Within the function you pull the string name for the channel then feed that string into a function that turns the original list into a dictionary that is just channel_name: number. It is that number that is used to generate the eventual PIMS Frame.

I don't understand why there is this number->list->string->dictionary->number organization when you can just use the number in the first place.

I deleted this middle process from my source and it now works exactly like I would expect it to.

I ran into this problem because I had two channels with the same name so the dictionary was always returning the same number even though there were two different channels. Of course, I _shouldn't_ have channels with the same name, but I honestly thought they had different names when I ran my experiment.

**Comment by rbnvrw** [comment]
This seems like a good enhancement to the package!
I'm not sure why the channels are handled this way, but it makes sense to cut out all the redundant stuff in the middle.

If you have time to organize your fix into a pull request, I would greatly appreciate it.
Otherwise I'll try to get it into a next release.

**Comment by jbf81tb** [comment]
Yeah, it would easy for me to work on that pull request and get it submitted within the next day or two. I'm glad that I might be able to help.

**Comment by rbnvrw** [comment]
Thanks again for your help! Your PR #15 was merged, closing this now.
