### ISSUE TITLE
Issues to Open stiched ND2 files

### ISSUE THREAD

**Issue by trasse** [rbnvrw/nd2reader#17]
Hi Ruben,

I can not open stitched Nd2 files from our Slidescanner in Python.
I use Python 3.6 and nd2reader=3.1.0.

This is the metadata that is read:

<Deprecated ND2 C:\Data\slidescanner\20190514_000911_813\Slide1-1-1_ChannelBrightfield_Seq0000.nd2>
Created: Unknown
Image size: 3302x5146 (HxW)
Frames: 1
Channels: Brightfield
Fields of View: 1
Z-Levels: 0

When I open the file the numpy array has this dimension:
(3302, 7720)

I have strange lines in the image.
The image is no longer RGB.

Images were acquired with NIS Elements 5.02.00.

Do you have any advise (other than using the dedicated Fiji Plugin…)

Thanks a lot &
Kind regards

Tobias

**Comment by rbnvrw** [comment]
Hi Tobias, 

Thank you for the bug report. 

Because I can only work with ND2 files that are generated by my microscope, more 'exotic' files such as the file you're trying to open may or may not work out of the box. If you can attach the ND2 file here or can upload it to a file sharing service, I can have a look at the file structure.

Hopefully that will shed some light on the issues you're having.

Best,
Ruben

**Comment by trasse** [comment]
Dear Ruben,

thanks a lot! That is very kind of you.
I will send you the file as download link!

Kind regards

Tobias

**Comment by rbnvrw** [comment]
Hi Tobias,

I have looked at the file you've send me, and have opened it with Bioformats in ImageJ, then it looks like this:

![imagej](https://user-images.githubusercontent.com/1511097/65226767-bdd96980-dac7-11e9-8c17-385b61631c9c.png)

With the latest nd2reader version, it looks like this when plotted with pyplot:

![nd2reader](https://user-images.githubusercontent.com/1511097/65226798-d0ec3980-dac7-11e9-9db6-60a92244b597.png)

The metadata I get is the following:
```
{'height': 3302, 'width': 5146, 'date': None, 'fields_of_view': [0], 'frames': [0], 'z_levels': [], 'z_coordinates': [-1967.65], 'total_images_per_channel': 1, 'channels': ['Brightfield'], 'pixel_microns': 11.00244498777506, 'num_frames': 1, 'experiment': {'description': '', 'loops': [{'start': 0, 'duration': 0, 'stimulation': False, 'sampling_interval': 0.0}]}, 'events': []}
```

If you want to try it with different files, I have used the following code to read and show the ND2 file:
```
from nd2reader import ND2Reader
nd2 = ND2Reader('Slide1-1-1_ChannelBrightfield_Seq0000.nd2')
print(nd2.metadata)
import matplotlib.pyplot as plt
plt.imshow(nd2[0], cmap='gray')
plt.show(block=True)
```

Could you please let me know if this is what you would expect to see for this image?
Thank you!

**Comment by trasse** [comment]
Dear Ruben,

thanks a lot! 
Now the image looks exactly as expected.

Kind regards
Tobias
