### ISSUE TITLE
in 3.2.0, get_frame_2D fails

### ISSUE THREAD

**Issue by tsvikas** [rbnvrw/nd2reader#25]
in `nd2reader/reader.py`, the function `get_frame_2D` in line 55 raises an error `NameError: name 'get_frame_vczyx' is not defined`

it seems to be a typo. the line 
`
return get_frame_vczyx(v=v, c=c, t=t, z=z, x=x, y=y)
`
should be 
`
return self.get_frame_vczyx(v=v, c=c, t=t, z=z, x=x, y=y)
`

**Comment by TeaWolf** [comment]
Indeed this seems to work right after the line change

**Comment by rbnvrw** [comment]
Thank you both for noticing and reporting this issue!

Fixed in commit 2af560aa68cf1ba7ba72cc51c85bd14d1a3a28f4

I'll add a unit test to prevent this in the future and make a new release

**Comment by rbnvrw** [comment]
This issue is now fixed in release 3.2.1
