### ISSUE TITLE
Bug in attempt to remove unwanted bytes

### ISSUE THREAD

**Issue by guiwitz** [rbnvrw/nd2reader#50]
Hi everyone,

first, thanks for this great library!

I think the recent PR #40 by @ggirelli introduced a bug in the library, as I'm not able anymore to read some multi-channel files. Specifically, when I open a file with ```nd2file = ND2Reader(fh)``` and try to get a given frame, the first channel works fine with ```nd2file.get_frame_2D(c=0)``` but the other channels like ```nd2file.get_frame_2D(c=1)``` fail with an error stating:

```AssertionError: An unexpected number of extra bytes was encountered based on the expected frame size, therefore the file could not be parsed.```

I had a look in the code and I think the offending line is here: https://github.com/rbnvrw/nd2reader/blob/df6d70e7d46dc4c97b99ab9e6f856d9333648650/nd2reader/stitched.py#L13

This line measures if there are any "remaining" pixels from the expected number width and height of the image. The problem is that the first ```image_data_start``` elements are skipped when measuring the image size and ```image_data_start``` depends on the chosen channel as defined here:
https://github.com/rbnvrw/nd2reader/blob/df6d70e7d46dc4c97b99ab9e6f856d9333648650/nd2reader/parser.py#L269

where ```4``` takes care of the standard 4 elements to skip because they correspond to the time stamp and ```channel_offset``` is just the channel index. 

Let's imagine the case of a 10x10 image with 2 channels and with *no pixels to remove*. Here:
```len(image_group_data)=4+2*10*10 = 204```.
If we consider the case ```c=0``` then:
```image_data_start = 4 + 0 = 4``` and therefore ```(len(image_group_data[4:])) % (height * width) = 0```. 
However if we now consider ```c=1``` then:
```image_data_start = 4 + 1 = 5``` and therefore ```(len(image_group_data[5:])) % (height * width) = 99```.

This is a long-winded explanation to say that I believe the offending line should simply be changed to:
```n_unwanted_bytes = (len(image_group_data[4:])) % (height * width)```
just like in the preceding one. I don't think that figuring out if there are pixels to remove should be depending on the selected channel. When I modified the code in this way I was again able to read all channesl.

I can open a PR if needed but it's probably easier if one of the maintainers checks if that's correct and directly fixes this tiny error.

**Comment by rbnvrw** [comment]
Thank you @guiwitz I agree with your analysis. It is fixed in the master now, I'll do a few checks and release a new version later today.
