### ISSUE TITLE
nd2reader outputs empty arrays for certain ND2 files.

### ISSUE THREAD

**Issue by zjniu** [rbnvrw/nd2reader#56]
Hello,

I am having some trouble reading certain ND2 files using nd2reader. It successfully reads the metadata, but when I index the image itself, an empty numpy array is outputted. [Here](https://github.com/zjniu/nd2reader-issue/blob/master/not_working.nd2) is an example of an image that doesn't work. [Here](https://github.com/zjniu/nd2reader-issue/blob/master/working.nd2) is a very similar example of an image that does work (a non-empty array is outputted).

Does anyone know why this is happening?

Thanks!

**Comment by zjniu** [comment]
Are there any updates on this issue?

**Comment by rbnvrw** [comment]
Thank you for the PR and apologies for the delay. I'm looking at the PR now.
