### ISSUE TITLE
Array shape

### ISSUE THREAD

**Issue by hanasha** [rbnvrw/nd2reader#6]
Hi, 
I have problems reading frames from:

imReader
<FramesSequenceND>
Axes: 3
Axis 'x' size: 973
Axis 'y' size: 973
Axis 't' size: 443
Pixel Datatype: <class 'numpy.float64'>

while asking for the first frame:
imReader[0]
I get an error ending with:
ValueError: cannot reshape array of size 947702 into shape (973,973)

Thanks!

**Comment by rbnvrw** [comment]
Thank you for your bug report. 

Can you post the output of:
```
imReader.bundle_axes
imReader.iter_axes
imReader.metadata
```

Thank you!

**Comment by hanasha** [comment]
The output looks as follows (with edited list of frames):

```
imReader.bundle_axes
['y', 'x']
imReader.iter_axes
['t']
imReader.metadata
{'channels': ['DIC cam'],
 'date': datetime.datetime(2018, 5, 28, 22, 23, 1),
 'experiment': {'description': '',
  'loops': [{'duration': 345600000.0,
    'sampling_interval': 600000.0,
    'start': 0,
    'stimulation': False}]},
 'fields_of_view': [0],
 'frames': [0,
  1,
  2,
  3,
...
  440,
  441,
  442],
 'height': 973,
 'num_frames': 443,
 'pixel_microns': 0.647298582015452,
 'total_images_per_channel': 443,
 'width': 973,
 'z_levels': []}
```

**Comment by rbnvrw** [comment]
Thank you for the information. The output looks fine, so I'll need the nd2 file to really debug it.

Please send the ND2 file to the temporary mail address avf697z@shitmail.org (e.g. via WeTransfer) and I'll have a look!

**Comment by rbnvrw** [comment]
Comment: the stack was collected using Jobs module of Elements using both binning (4) and stitching (2x2). The file can be open both by Elements and ImageJ (BioFormats) and the shape is as specified in metadata.

**Comment by rbnvrw** [comment]
@hanasha I'm not sure what is causing the problem, but I've added a workaround that at least let's you open the file. Can you test with the latest development code from the master branch on GitHub if you can also open your file now?
