### ISSUE TITLE
Reading 'date' in metadata fails within PyQt5.QWidgets.QApplication

### ISSUE THREAD

**Issue by LeBarbouze** [rbnvrw/nd2reader#7]
The 'date' entry from `images.metadata` is `None` when ND2Reader is used after `QApplication` has been instantied. All other fields in `images.metadata` are read normally and the image array is also correctly read, as far as I can judge.

Here is a code snippet that shows the problem:

```python
import sys

from PyQt5.QtWidgets import QApplication, QWidget
from nd2reader import ND2Reader
from pathlib import Path


def load(path):
    with ND2Reader(path) as images:
        date = images.metadata['date']
        weird = date is None
        print(date, ', weird: {}'.format(weird))
        for index, arr in enumerate(images):
            print('{:02d}. detected image shape: {}'.format(index, arr.shape))


if __name__ == '__main__':
    path = Path('~/temp/microscopy.nd2').expanduser()

    print('outside loop')
    load(path)  # first: outside pyqt5 main loop
    print()

    print('inside loop')
    app = QApplication(sys.argv)
    load(path)  # second: inside pyqt5 main loop
    widget = QWidget()
    widget.show()  # produces an empty widget for the sake of demonstration
    sys.exit(app.exec_())
```

Here is the output when I execute the code from a terminal:
```bash
mycomputer~/temp$ python nd2pyqt5bug.py 
outside loop
2018-03-23 10:36:34 , weird: False
00. detected image shape: (2044, 2048)
01. detected image shape: (2044, 2048)

inside loop
None , weird: True
00. detected image shape: (2044, 2048)
01. detected image shape: (2044, 2048)
```
and the images are correctly plotted (from what I can judge) so I suppose there is no other mistake that reading the bytes associated with the date.

Perhaps the `QApplication` main loop interferes with the datetime reading? (though no error pops up)

Context:
* OS : macOS 10.13.5
* `python -V` returns `Python 3.6.4 :: Anaconda, Inc.` (installed from miniconda)
* installed packages:
    - `pyqt                      5.9.2            py36h11d3b92_0`
    - `nd2reader                 3.0.9                      py_0    conda-forge`

(edit) PS: except that tiny bug, which looks like to be `pyqt`'s fault, good work!

**Comment by rbnvrw** [comment]
Thank you for this bug report. I have not been able to reproduce it on my system, but I don't own a Mac so maybe it's related to the OS.
If you have the time to look into it yourself, I'd be happy to accept a pull request.
