### ISSUE TITLE
Z resolution (sampling over Z)

### ISSUE THREAD

**Issue by ggirelli** [rbnvrw/nd2reader#8]
Hello there and thanks for this awesome package! I went through the documentation and the code, and the only thing I could not find is how to extract from the metadata the resolution in the third dimension. Did I miss something? Can it be easily added as a new feature? Thanks! :)

**Comment by ggirelli** [comment]
Found out how to get the info. Thanks again! :D
```
fh = open("path.nd2", "rb")
p = Parser(fh)
p._raw_metadata.z_data # Z coordinate of each slice
np.diff(p._raw_metadata.z_data.tolist()) # Distance between slices
# ^^^ This should be constant!
```

**Comment by rbnvrw** [comment]
Thank you and I'm glad you figured it out!
